version: '3.7'
services:
  nginx:
    image: johnnyworks/nginx:alpine
    restart: always
    container_name: my-nginx
    ulimits:
      nofile:
        soft: 10240
        hard: 10240
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./www:/data
      - ./conf:/etc/nginx/conf.d
    logging:
      driver: 'json-file'
      options:
        max-file: '2'
        max-size: '2m'
    networks:
      - default
  php:
    image: johnnyworks/php56-fpm:alpine
    restart: always
    container_name: my-php-fpm
    ulimits:
      nofile:
        soft: 10240
        hard: 10240
    volumes:
      - ./www:/data
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./phpfpm.conf:/usr/local/etc/php-fpm.d/www.conf
    logging:
      driver: 'json-file'
      options:
        max-file: '2'
        max-size: '2m'
    networks:
      - default
networks:
  default:
